Repository nonoro/bookmanbo_BE, pull requests merged in 2023-01, with the labels that each got.

#2 도메인 설계
  src/main/java/toyproject1/bookmanbo/BookmanboApplication.java
  src/main/java/toyproject1/bookmanbo/config/JpaConfiguration.java
  src/main/java/toyproject1/bookmanbo/domain/Period.java
  src/main/java/toyproject1/bookmanbo/domain/Status.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Account.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Book.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Keyword.java
  src/main/java/toyproject1/bookmanbo/domain/entity/MyBook.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Note.java
  src/main/java/toyproject1/bookmanbo/domain/entity/NoteKeyword.java
  src/main/resources/application.yaml
  src/test/java/toyproject1/bookmanbo/BookmanboApplicationTests.java
Labels: enhancement

#4 도메인 수정
  src/main/java/toyproject1/bookmanbo/domain/entity/MyBook.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Note.java
Labels: duplicate

#8 Note 도메인 테스트
  src/main/java/toyproject1/bookmanbo/domain/entity/Account.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Book.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Keyword.java
  src/main/java/toyproject1/bookmanbo/domain/entity/MyBook.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Note.java
  src/main/java/toyproject1/bookmanbo/domain/entity/NoteKeyword.java
  src/main/java/toyproject1/bookmanbo/repository/AccountRepository.java
  src/main/java/toyproject1/bookmanbo/repository/KeywordRepository.java
  src/main/java/toyproject1/bookmanbo/repository/NoteKeywordRepository.java
  src/main/java/toyproject1/bookmanbo/repository/NoteRepository.java
  src/test/java/toyproject1/bookmanbo/config/JpaConfiguration.java
  src/test/java/toyproject1/bookmanbo/domain/entity/NoteTest.java
  src/test/java/toyproject1/bookmanbo/repository/KeywordRepositoryTest.java
  src/test/java/toyproject1/bookmanbo/repository/NoteRepositoryTest.java
Labels: enhancement

#17 note api 구현
  build.gradle
  src/main/java/toyproject1/bookmanbo/domain/entity/Book.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Keyword.java
  src/main/java/toyproject1/bookmanbo/domain/entity/MyBook.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Note.java
  src/main/java/toyproject1/bookmanbo/domain/entity/NoteKeyword.java
  src/main/java/toyproject1/bookmanbo/note/controller/MyBookController.java
  src/main/java/toyproject1/bookmanbo/note/controller/NoteController.java
  src/main/java/toyproject1/bookmanbo/note/dto/request/NoteRequest.java
  src/main/java/toyproject1/bookmanbo/note/dto/response/BookResponse.java
  src/main/java/toyproject1/bookmanbo/note/dto/response/MyBookResponse.java
  src/main/java/toyproject1/bookmanbo/note/dto/response/NoteResponse.java
  src/main/java/toyproject1/bookmanbo/note/dto/response/Response.java
  src/main/java/toyproject1/bookmanbo/note/service/MyBookService.java
  src/main/java/toyproject1/bookmanbo/note/service/NoteService.java
  src/main/resources/application.yaml
  src/test/java/toyproject1/bookmanbo/repository/NoteRepositoryTest.java
Labels: enhancement

#20 Book 도메인 수정
  build.gradle
  src/main/java/toyproject1/bookmanbo/aladin/AladinClient.java
  src/main/java/toyproject1/bookmanbo/aladin/dto/request/ItemListReq.java
  src/main/java/toyproject1/bookmanbo/aladin/dto/request/ItemLookUpReq.java
  src/main/java/toyproject1/bookmanbo/aladin/dto/request/ItemSearchReq.java
  src/main/java/toyproject1/bookmanbo/aladin/dto/response/ItemListRes.java
  src/main/java/toyproject1/bookmanbo/aladin/dto/response/ItemLookUpRes.java
  src/main/java/toyproject1/bookmanbo/aladin/dto/response/ItemSearchRes.java
  src/main/java/toyproject1/bookmanbo/domain/entity/Book.java
  src/main/java/toyproject1/bookmanbo/note/dto/response/BookResponse.java
  src/main/resources/application.yaml
  src/test/java/toyproject1/bookmanbo/BookmanboApplicationTests.java
  src/test/java/toyproject1/bookmanbo/aladin/AladinClientTest.java
  src/test/java/toyproject1/bookmanbo/repository/BookRepositoryTest.java
  src/test/java/toyproject1/bookmanbo/repository/NoteRepositoryTest.java
  src/test/resources/application.yaml
Labels: duplicate, enhancement
